name: ng_poland_conf_app
description: NG an JS Poland Conference official app.
publish_to: "none"
version: 1.0.7+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0

  go_router: ^9.0.0

  injectable: ^2.1.2
  get_it: ^7.6.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.12

  font_awesome_flutter: ^10.5.0
  cached_network_image: ^3.3.0
  rive: ^0.12.4

  hive:
  hive_flutter:

  cloud_firestore: ^4.15.8
  dio: ^5.2.1+1
  retrofit: ">=4.0.0 <5.0.0"
  logger:

  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.4
  webview_flutter: ^4.4.1
  connectivity_plus: ^5.0.1
  collection: ^1.17.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  retrofit_generator: ">=5.0.0 <6.0.0"
  json_serializable: ^6.7.1

  injectable_generator:
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/dark/
    - assets/icons/light/
    - assets/images/authors/
    - assets/animations/rive/
    - env
