name: ng_poland_conf_app
description: NG an JS Poland Conference official app.
publish_to: "none"
version: 1.2.0+13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: 3.14.0
  firebase_auth: 5.6.0
  cloud_firestore: 5.6.9

  # Auth
  google_sign_in: 6.3.0
  sign_in_with_apple: 7.0.1

  # Routing
  go_router: 15.2.3

  # Dependency Injection
  injectable: 2.5.0
  get_it: 8.0.3

  # Utils
  flutter_dotenv: 5.2.1
  intl: 0.20.2
  url_launcher: 6.3.0
  logger: 1.4.0
  collection: 1.19.0
  dartz: 0.10.1

  # UI
  font_awesome_flutter: 10.8.0
  cached_network_image: 3.4.1
  # rive: 0.14.0-dev.12 // TODO: fix Rive 0.14 migration
  webview_flutter: 4.9.0
  connectivity_plus: 6.1.4

  # Hive (local storage)
  hive: 2.2.3
  hive_flutter: 1.1.0

  # Networking
  dio: 5.8.0+1
  retrofit: 4.4.2

  # Bloc (state management)
  bloc: 9.0.0
  flutter_bloc: 9.1.1
  bloc_concurrency: 0.3.0
  rxdart: 0.28.0

  # Codegen annotations
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

  # Codegen
  build_runner: 2.4.15
  freezed: 2.5.7
  retrofit_generator: 9.2.0
  json_serializable: 6.9.0
  hive_generator: 2.0.1
  injectable_generator: 2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/dark/
    - assets/icons/light/
    - assets/images/authors/
    - assets/animations/rive/
    - env
