name: ng_poland_conf_app
description: NG an JS Poland Conference official app.
publish_to: "none"
version: 1.2.1+14

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: 3.14.0
  firebase_auth: 5.6.0
  cloud_firestore: 5.6.9

  # Auth
  google_sign_in: 6.3.0
  sign_in_with_apple: 7.0.1

  # Routing
  go_router: 15.2.3

  # Dependency Injection
  injectable: 2.5.2
  get_it: 8.2.0

  # Utils
  flutter_dotenv: 5.2.1
  intl: 0.20.2
  url_launcher: 6.3.0
  logger: 1.4.0
  collection: 1.19.1
  dartz: 0.10.1

  # UI
  font_awesome_flutter: 10.8.0
  cached_network_image: 3.4.1
  # rive: 0.14.0-dev.12 // TODO: fix Rive 0.14 migration
  webview_flutter: 4.9.0
  connectivity_plus: 6.1.4


  # Networking
  dio: 5.8.0+1
  retrofit: 4.8.0

  # Bloc (state management)
  bloc: 9.0.0
  flutter_bloc: 9.1.1
  bloc_concurrency: 0.3.0
  rxdart: 0.28.0

  # Codegen annotations
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0

  #hive
  hive_ce_flutter: ^2.3.3
  hive_ce: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

  # Codegen
  build_runner: 2.10.1
  freezed: 3.2.3
  retrofit_generator: 10.1.1
  json_serializable: 6.11.1
  injectable_generator: 2.9.0
  hive_ce_generator: ^1.10.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/dark/
    - assets/icons/light/
    - assets/images/authors/
    - assets/animations/rive/
    - env
