// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhErzqwmC7sALF50ed7de0z1APvG8Kln4',
    appId: '1:416351507920:web:7f0f314250c20dbeed95d5',
    messagingSenderId: '416351507920',
    projectId: 'ngpolandconfapp',
    authDomain: 'ngpolandconfapp.firebaseapp.com',
    storageBucket: 'ngpolandconfapp.firebasestorage.app',
    measurementId: 'G-N51J485X9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_0-ChrLuRSdkZPadSIut7TTFxNAtRwAw',
    appId: '1:416351507920:android:27d98bf1f4acd702ed95d5',
    messagingSenderId: '416351507920',
    projectId: 'ngpolandconfapp',
    storageBucket: 'ngpolandconfapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUxUYNEpC_SNRdgsYVgaELPKXvpps_AXE',
    appId: '1:416351507920:ios:2a24ee768f0dfbe0ed95d5',
    messagingSenderId: '416351507920',
    projectId: 'ngpolandconfapp',
    storageBucket: 'ngpolandconfapp.firebasestorage.app',
    androidClientId: '416351507920-btm09gpd133ea5onoi75oiv7c0bg0h7e.apps.googleusercontent.com',
    iosClientId: '416351507920-m8hrt7lp3ei07pdvb51qq1pskrt6bil0.apps.googleusercontent.com',
    iosBundleId: 'com.mvpgreenhouse.ngPolandConfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUxUYNEpC_SNRdgsYVgaELPKXvpps_AXE',
    appId: '1:416351507920:ios:2a24ee768f0dfbe0ed95d5',
    messagingSenderId: '416351507920',
    projectId: 'ngpolandconfapp',
    storageBucket: 'ngpolandconfapp.firebasestorage.app',
    androidClientId: '416351507920-btm09gpd133ea5onoi75oiv7c0bg0h7e.apps.googleusercontent.com',
    iosClientId: '416351507920-m8hrt7lp3ei07pdvb51qq1pskrt6bil0.apps.googleusercontent.com',
    iosBundleId: 'com.mvpgreenhouse.ngPolandConfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP1_z_3kxpU__BaUSQUOAdaYH9LdFk1_o',
    appId: '1:416351507920:web:9c1db2912bb02feced95d5',
    messagingSenderId: '416351507920',
    projectId: 'ngpolandconfapp',
    authDomain: 'ngpolandconfapp.firebaseapp.com',
    storageBucket: 'ngpolandconfapp.firebasestorage.app',
    measurementId: 'G-0HPQ8QK5T5',
  );
}
