// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ng_poland_conf_app/features/home/datasources/models/conference_home_page_schedule_item_model.dart';
import 'package:ng_poland_conf_app/features/home/datasources/models/conference_model.dart';
import 'package:ng_poland_conf_app/features/home/datasources/models/conferences_model.dart';
import 'package:ng_poland_conf_app/features/info/datasources/models/info_item_model.dart';
import 'package:ng_poland_conf_app/features/info/datasources/models/info_items_model.dart';
import 'package:ng_poland_conf_app/features/nggirls/datasources/models/ngGirls_model.dart';
import 'package:ng_poland_conf_app/features/schedule/datasources/models/event_item_model.dart';
import 'package:ng_poland_conf_app/features/schedule/datasources/models/events_model.dart';
import 'package:ng_poland_conf_app/features/speakers/datasources/models/speaker_model.dart';
import 'package:ng_poland_conf_app/features/speakers/datasources/models/speakers_model.dart';
import 'package:ng_poland_conf_app/features/workshops/datasources/models/workshop_model.dart';
import 'package:ng_poland_conf_app/features/workshops/datasources/models/workshops_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ConferenceHomePageScheduleItemModelAdapter());
    registerAdapter(ConferenceModelAdapter());
    registerAdapter(ConferencesModelAdapter());
    registerAdapter(EventItemModelAdapter());
    registerAdapter(EventsModelAdapter());
    registerAdapter(InfoItemModelAdapter());
    registerAdapter(InfoItemsModelAdapter());
    registerAdapter(NgGirlsModelAdapter());
    registerAdapter(SpeakerModelAdapter());
    registerAdapter(SpeakersModelAdapter());
    registerAdapter(WorkshopModelAdapter());
    registerAdapter(WorkshopsModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ConferenceHomePageScheduleItemModelAdapter());
    registerAdapter(ConferenceModelAdapter());
    registerAdapter(ConferencesModelAdapter());
    registerAdapter(EventItemModelAdapter());
    registerAdapter(EventsModelAdapter());
    registerAdapter(InfoItemModelAdapter());
    registerAdapter(InfoItemsModelAdapter());
    registerAdapter(NgGirlsModelAdapter());
    registerAdapter(SpeakerModelAdapter());
    registerAdapter(SpeakersModelAdapter());
    registerAdapter(WorkshopModelAdapter());
    registerAdapter(WorkshopsModelAdapter());
  }
}
