import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:injectable/injectable.dart';
import 'package:hive_ce_flutter/adapters.dart';
import 'package:ng_poland_conf_app/core/blocks/conferences/conferences_cubit.dart';
import 'package:ng_poland_conf_app/features/edition/presentation/edition_cubit.dart';
import 'package:ng_poland_conf_app/features/home/presentation/first_launch_offline_page.dart';
import 'package:ng_poland_conf_app/core/blocks/themeMode/theme_mode_cubit.dart';
import 'package:ng_poland_conf_app/features/authentication/presentation/cubit/user_session_cubit.dart';
import 'package:ng_poland_conf_app/features/authentication/presentation/services/magic_link_deep_link_listener.dart';
import 'package:ng_poland_conf_app/core/constants/hive_constants.dart';
import 'package:ng_poland_conf_app/injectable.dart';
import 'package:ng_poland_conf_app/routing/routing.dart';
import 'package:ng_poland_conf_app/theme/app_palette.dart';
import 'package:ng_poland_conf_app/theme/theme.dart';
import 'package:timezone/data/latest.dart' as tzdata;
import 'firebase_options.dart'; // Import the generated file

Future<void> dropLegacyContentfulBoxes() async {
  for (final name in HiveConstantsForBoxes.legacyContentBoxes) {
    try {
      if (await Hive.boxExists(name)) {
        await Hive.deleteBoxFromDisk(name);
      }
    } catch (_) {}
  }
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await GoogleSignIn.instance.initialize();
  await Hive.initFlutter();
  await dropLegacyContentfulBoxes();

  // This function, generated by injectable, registers all your dependencies (like ConferencesCubit) with GetIt.
  await configureDependencies(
    Environment.prod,
  ); // Replace 'Environment.prod' with the appropriate argument for your setup.

  tzdata.initializeTimeZones();

  getIt.get<UserSessionCubit>().stream.listen(
    (_) => getIt.get<Routing>().router.refresh(),
  );
  await getIt.get<MagicLinkDeepLinkListener>().start();

  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  @override
  void initState() {
    super.initState();
    getIt.get<ConferencesCubit>().getConferences();
  }

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (context) => getIt.get<ConferencesCubit>()),
        BlocProvider(create: (context) => getIt.get<EditionCubit>()),
        BlocProvider(
          create: (context) => getIt.get<ThemeModeCubit>()..getThemeMode(),
        ),
        BlocProvider(create: (_) => getIt.get<UserSessionCubit>()),
      ],
      child: BlocBuilder<ThemeModeCubit, ThemeModeState>(
        builder: (context, state) {
          return state.when(
            initial: () => const SizedBox.shrink(),
            loaded: (themeMode) => MaterialApp.router(
              routerConfig: getIt.get<Routing>().router,
              builder: (context, child) {
                return BlocBuilder<EditionCubit, EditionState>(
                  builder: (context, editionState) {
                    if (editionState is EditionFailed) {
                      return const FirstLaunchOfflinePage();
                    }
                    return child ?? const SizedBox.shrink();
                  },
                );
              },
              theme: ThemeData(
                useMaterial3: true,
                colorScheme: lightColorScheme,
                appBarTheme: const AppBarTheme(
                  backgroundColor: Color(0xff4f00d0),
                  foregroundColor: Color(0xfffdfdfd),
                  shadowColor: Color(0xfffafafb),
                ),
                applyElevationOverlayColor: false,
                bottomNavigationBarTheme: const BottomNavigationBarThemeData(
                  backgroundColor: Color(0xff4f00d0),
                  selectedItemColor: Color(0xfffdfdfd),
                  unselectedItemColor: Color(0x8a9a7bff),
                ),
                buttonTheme: const ButtonThemeData(
                  alignedDropdown: false,
                  colorScheme: lightButtonColorScheme,
                ),
                filledButtonTheme: FilledButtonThemeData(
                  style: FilledButton.styleFrom(
                    backgroundColor: lightButtonColorScheme.primary,
                    foregroundColor: Colors.white,
                    disabledBackgroundColor: lightButtonColorScheme.primary
                        .withValues(alpha: 0.38),
                    disabledForegroundColor: Colors.white.withValues(
                      alpha: 0.38,
                    ),
                  ),
                ),
                switchTheme: SwitchThemeData(
                  thumbColor: WidgetStateProperty.resolveWith((states) {
                    if (states.contains(WidgetState.selected)) {
                      return Colors.white;
                    }
                    return lightColorScheme.outline;
                  }),
                  trackColor: WidgetStateProperty.resolveWith((states) {
                    if (states.contains(WidgetState.selected)) {
                      return lightColorScheme.secondary;
                    }
                    return lightColorScheme.surfaceContainerHighest;
                  }),
                  trackOutlineColor: WidgetStateProperty.resolveWith((states) {
                    if (states.contains(WidgetState.selected)) {
                      return Colors.transparent;
                    }
                    return lightColorScheme.outline;
                  }),
                ),
                dividerTheme: DividerThemeData(
                  color: lightColorScheme.secondary,
                  thickness: 1.0,
                  space: 0.0,
                  indent: 0.0,
                  endIndent: 0.0,
                ),
                textTheme: TextTheme(
                  displayLarge: const TextStyle(
                    fontSize: 42,
                    fontWeight: FontWeight.bold,
                  ),
                  titleLarge: TextStyle(
                    fontSize: 30,
                    fontWeight: FontWeight.bold,
                    color: lightColorScheme.onSecondary,
                  ),
                  bodyMedium: const TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.normal,
                  ),
                  bodySmall: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.normal,
                  ),
                  displayMedium: const TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                  titleMedium: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: lightColorScheme.onPrimary,
                  ),
                  displaySmall: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.normal,
                  ),
                ),
                extensions: const [AppPalette.light],
              ),
              darkTheme: ThemeData(
                useMaterial3: true,
                colorScheme: darkColorScheme,
                appBarTheme: const AppBarTheme(
                  backgroundColor: Color(0xffE91E63),
                  foregroundColor: Color(0xfffdfdfd),
                  shadowColor: Color(0xfffafafb),
                ),
                applyElevationOverlayColor: false,
                bottomNavigationBarTheme: const BottomNavigationBarThemeData(
                  backgroundColor: Color(0xff4f00d0),
                  selectedItemColor: Color(0xfffdfdfd),
                  unselectedItemColor: Color(0x8a9a7bff),
                ),
                buttonTheme: const ButtonThemeData(
                  alignedDropdown: false,
                  colorScheme: darkButtonColorScheme,
                ),
                // Dark ColorScheme.primary is near-white (#FFEDEB); brand
                // purple/pink keep FilledButton and Switch readable.
                filledButtonTheme: FilledButtonThemeData(
                  style: FilledButton.styleFrom(
                    backgroundColor: darkButtonColorScheme.primary,
                    foregroundColor: darkButtonColorScheme.onPrimary,
                    disabledBackgroundColor: darkButtonColorScheme.primary
                        .withValues(alpha: 0.38),
                    disabledForegroundColor: darkButtonColorScheme.onPrimary
                        .withValues(alpha: 0.38),
                  ),
                ),
                switchTheme: SwitchThemeData(
                  thumbColor: WidgetStateProperty.resolveWith((states) {
                    if (states.contains(WidgetState.selected)) {
                      return Colors.white;
                    }
                    return darkColorScheme.outline;
                  }),
                  trackColor: WidgetStateProperty.resolveWith((states) {
                    if (states.contains(WidgetState.selected)) {
                      return darkColorScheme.primaryContainer;
                    }
                    return darkColorScheme.surfaceContainerHighest;
                  }),
                  trackOutlineColor: WidgetStateProperty.resolveWith((states) {
                    if (states.contains(WidgetState.selected)) {
                      return Colors.transparent;
                    }
                    return darkColorScheme.outline;
                  }),
                ),
                dividerTheme: DividerThemeData(
                  color: darkColorScheme.primary,
                  thickness: 1.0,
                  space: 0.0,
                  indent: 0.0,
                  endIndent: 0.0,
                ),
                textTheme: TextTheme(
                  displayLarge: const TextStyle(
                    fontSize: 42,
                    fontWeight: FontWeight.bold,
                  ),
                  titleLarge: TextStyle(
                    fontSize: 30,
                    fontWeight: FontWeight.bold,
                    color: Theme.of(context).colorScheme.onSecondary,
                  ),
                  bodyMedium: const TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.normal,
                  ),
                  bodySmall: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.normal,
                  ),
                  displayMedium: const TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                  titleMedium: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Theme.of(context).colorScheme.onPrimary,
                  ),
                  displaySmall: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.normal,
                  ),
                ),
                extensions: const [AppPalette.dark],
              ),
              themeMode: themeMode,
              debugShowCheckedModeBanner: false,
            ),
          );
        },
      ),
    );
  }
}
