name: Flutter action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/ng_poland_conf_app
      - name: Create .env file
        run: |
          cat > ./.env <<EOF
          access_token=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          space_id=${{ secrets.CONTENTFUL_SPACE_ID }}
          api_url=${{ secrets.API_URL }}
          EOF
      
      # uncomment when we have tests
      # - run: flutter test
      #  working-directory: ${{ github.workspace }}/ng_poland_conf_app
      - run: flutter build apk
        working-directory: ${{ github.workspace }}/ng_poland_conf_app
      - run: flutter build appbundle
        working-directory: ${{ github.workspace }}/ng_poland_conf_app
