name: Flutter action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
uses: subosito/flutter-action@v2.11.0
with:
    flutter-version: '3.7.7'
    channel: 'stable'
run: flutter --version
