name: Flutter CI (web)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/ng_poland_conf_app
      - name: Create .env file
        run: |
          cat > ${{ github.workspace }}/ng_poland_conf_app/env <<EOF
          access_token=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          space_id=${{ secrets.CONTENTFUL_SPACE_ID }}
          api_url=${{ secrets.API_URL }}
          EOF
      
      # uncomment when we have tests
      # - run: flutter test
      #  working-directory: ${{ github.workspace }}/ng_poland_conf_app
      - run: flutter build web
        working-directory: ${{ github.workspace }}/ng_poland_conf_app
